PuntoVenta/Models/Ventas/VenVenta.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using PuntoVenta.Models.Productos;

namespace PuntoVenta.Models.Ventas
{
    public class VenVenta
    {

        [Key]
        public int idVenVenta { get; set; }
        public int idUsuUsuario { get; set; }
        public string strFolio { get; set; }
        public DateTime dtFecha { get; set; }
        public int idVenCatEstado { get; set; }
    }
}

PuntoVenta/Models/Ventas/VenVentaProducto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PuntoVenta.Models.Ventas
{
    public class VenVentaProducto
    {
        [Key]
        public int idVenVentaProducto { get; set; }
        public int idVenVenta { get; set; }
        public int idProProducto { get; set; }
        public decimal decCantidad { get; set; }
        public decimal curTotal { get; set; }
    }
}

PuntoVenta/Models/Ventas/VentaViewModel.cs
namespace PuntoVenta.Models.Ventas
{
    public class VentaViewModel
    {
        public List<ProductoVenta> Productos { get; set; }
        public string Folio { get; set; } // Agregar la propiedad Folio

        public int UserId { get; set; }

    }

    public class ProductoVenta
    {   public decimal Stock { get; set; }
        public int IdProProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
    }

}

PuntoVenta/Models/Ventas/venCatEstado.cs
using System.ComponentModel.DataAnnotations;

namespace PuntoVenta.Models.Ventas
{
    public class venCatEstado
    {
        [Key]
        public int idVenCatEstado { get; set; }
        public string strNombre { get; set; }
        public string strDescripcion { get; set; }

    }
}

PuntoVenta/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PuntoVenta.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using PuntoVenta.ViewModels;
using PuntoVenta.Helpers;
using PuntoVenta.Servicios;



namespace PuntoVenta.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly ILogger<UsuariosController> _logger;
        //private readonly ServicioToken _tokenService;

        public UsuariosController(ApplicationDbContext context, ILogger<UsuariosController> logger//, ServicioToken tokenService
            )
        {
            _context = context;
            _logger = logger;
            //_tokenService = tokenService;
        }
        

      

        public IActionResult Index(int pagina = 1)
        {
            int totalRegistros = _context.UsuUsuario.Count();
            int registroPorPagina = 10;
            int totalPaginas = (int)Math.Ceiling((double)totalRegistros / registroPorPagina);


            List<UsuarioViewModel> usuarios = _context.UsuUsuario
                .Include(u => u.Estado)
                .Include(u => u.TipoUsuario)
                .Select(u => new UsuarioViewModel
                {
                    Id = u.Id,
                    strNombre = u.strNombre,
                    NombreEstado = u.Estado.strNombreEstado,
                    NombreTipoUsuario = u.TipoUsuario.strTipoUsuario
                })
                .Skip((pagina - 1) * registroPorPagina)
                .Take(registroPorPagina)
                .ToList();

            ViewBag.PaginaActual = pagina;
            ViewBag.TotalPaginas = totalPaginas;

            return View(usuarios);
        }



        private int ObtenerIdEstado()
        {
            var estadoDefecto = _context.UsuCatEstado.FirstOrDefault(e => e.strNombreEstado.Equals("Activo"));
            if (estadoDefecto == null)
            {
                throw new InvalidOperationException("No se encontro el estado por defecto");
            }
            return estadoDefecto.Id;

        }

        private int ObtenerIdTipoUsuario()
        {
            var tipoUsuarioD = _context.UsuCatTipoUsuario.FirstOrDefault(t => t.strTipoUsuario.Equals("Usuario Normal"));
            if (tipoUsuarioD == null)
            {
                throw new InvalidOperationException("No se encontro el estado por defecto");
            }
            return tipoUsuarioD.Id;
        }


       
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            string username = model.Username;
            HttpContext.Session.SetString("Username", username);
            var user = _context.UsuUsuario.Any(u => u.strNombre == username && u.strPassword == model.Password);
            
            if (user)
            {
                TempData["Mensaje"] = "Bienvenido, " + model.Username + "";
                
                Console.WriteLine($"Nombre de usuario Almacenado en la session: {username}");
                return RedirectToAction("Index","Home");
                //return RedirectToAction("CrearVenta", "Ventas");
                
            }
            else
            {
                ModelState.AddModelError("", "Nombre de usuario y/o contraseña incorrectos.");
                TempData["MensajeErrorL"] = "Nombre de usuario y/o contraseña incorrecto";
                Console.WriteLine("Credenciales incorrectas");
                return View(model);
            }
        }

        

        public IActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = _context.UsuUsuario.Find(id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarBorrar(int id)
        {
            var usuario = _context.UsuUsuario.Find(id);
            _context.UsuUsuario.Remove(usuario);
            _context.SaveChanges();
            TempData["MensajeBorrar"] = "¡Se ha eliminado al usuario, " + "!";
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.UsuUsuario.Any(e => e.Id == id);
        }



        public ActionResult Create()
        {
            ViewBag.Estado = _context.UsuCatEstado
        .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.strNombreEstado })
        .ToList();
            ViewBag.TipoUsuario = _context.UsuCatTipoUsuario
                        .Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.strTipoUsuario })
                        .ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario usuario)
        {
            string errorMessage = "";

            if (ModelState.IsValid)
            {
                if (usuario.IdUsuCatEstado == 0 && usuario.IdUsuCatTipoUsuario == 0)
                {
                    ModelState.AddModelError("EstadoId", "Debe seleccionar un estado.");
                    ModelState.AddModelError("TipoUsuario", "Debe seleccionar un tipo de usuario.");
                    ViewBag.Estado = _context.UsuCatEstado
                        .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.strNombreEstado })
                        .ToList();
                    ViewBag.TipoUsuario = _context.UsuCatTipoUsuario
                                .Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.strTipoUsuario })
                                .ToList();
                    return View(usuario);
                }

                usuario.strPassword = Encriptacion.Encriptar(usuario.strPassword);
            }
            else
            {
                errorMessage = "ModelState.IsValid fue falso. Los errores de validación son los siguientes:";
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errorMessage += $" {error.ErrorMessage}";
                    }
                }
            }

            try
            {
                
                _context.UsuUsuario.Add(usuario);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                errorMessage += $" Ocurrió un error al guardar el usuario en la base de datos: {ex.Message}.";
            }

            ModelState.AddModelError("", $"Ocurrió un error: {errorMessage} Por favor, inténtelo de nuevo más tarde.");

            ViewBag.Estado = _context.UsuCatEstado
                .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.strNombreEstado })
                .ToList();
            ViewBag.TipoUsuario = _context.UsuCatTipoUsuario
                        .Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.strTipoUsuario })
                        .ToList();
            return View(usuario);
        }


        public ActionResult CreateL()
        {
            ViewBag.Estado = _context.UsuCatEstado
        .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.strNombreEstado })
        .ToList();
            ViewBag.TipoUsuario = _context.UsuCatTipoUsuario
                        .Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.strTipoUsuario })
                        .ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateL(Usuario usuario)
        {
            string errorMessage = "";

            if (ModelState.IsValid)
            {
                if (usuario.IdUsuCatEstado == 0 && usuario.IdUsuCatTipoUsuario == 0)
                {
                    ModelState.AddModelError("EstadoId", "Debe seleccionar un estado.");
                    ModelState.AddModelError("TipoUsuario", "Debe seleccionar un tipo de usuario.");
                    ViewBag.Estado = _context.UsuCatEstado
                        .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.strNombreEstado })
                        .ToList();
                    ViewBag.TipoUsuario = _context.UsuCatTipoUsuario
                                .Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.strTipoUsuario })
                                .ToList();
                    return View(usuario);
                }
            }
            else
            {
                errorMessage = "ModelState.IsValid fue falso. Los errores de validación son los siguientes:";
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errorMessage += $" {error.ErrorMessage}";
                    }
                }
            }

            try
            {

                _context.UsuUsuario.Add(usuario);
                _context.SaveChanges();
                TempData["MensajeCrear"] = "¡Se ha registrado al usuario, "+ usuario + "!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

PuntoVenta/Controllers/VentasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Constraints;
using PuntoVenta.Models.Ventas;

namespace PuntoVenta.Controllers
{
    public class VentasController : Controller
    {
        
    }
}

PuntoVenta/Views/Ventas/detalleVentas.cshtml
@model List<PuntoVenta.Models.Productos.Products>
@{
    ViewBag.Title = "ventas";
}
<h2>@ViewBag.Title</h2>

<head>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
</head>


    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PuntoVenta</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Productos">Productos</a>
                        </li>

                       

                    </ul>
                </div>
            </div>
        </nav>
    </header>

<div>
    @Html.ActionLink("Crear Venta", "Ventas", "Productos", null, new { @class = "btn btn-primary" })
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>    
                <th>Folio</th>
                <th>Fecha</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var venta in ViewBag.Ventas)
            {
                <tr>
                    <td>@venta.strFolio</td>
                    <td>@venta.dtFecha</td>
                    <td>@venta.EstadoNombre</td>
                    <td>
                        <form method="post" asp-action="CancelarVenta" asp-route-strFolio="@venta.strFolio">
                            <button type="submit" class="btn btn-danger">Cancelar Venta</button>
                        </form>
                    </td>
                    <td>
                        <a href="@Url.Action("GenerarPdfVenta", "Productos", new { strFolio = @venta.strFolio })" class="btn btn-secondary">Descargar PDF</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script>
    // Agrega una función JavaScript para cancelar la venta
    function cancelarVenta(idVenta) {
        if (confirm("¿Estás seguro de querer cancelar esta venta?")) {
            fetch("/Ventas/CancelarVenta/" + idVenta, { // Reemplaza "/Ventas/CancelarVenta/" con la ruta correcta en tu aplicación
                method: "POST"
            }).then(response => {
                if (response.ok) {
                    // Recargar la página después de cancelar la venta
                    window.location.reload();
                } else {
                    alert("Error al cancelar la venta.");
                }
            }).catch(error => {
                console.error("Error:", error);
                alert("Error al cancelar la venta.");
            });
        }
    }
</script>

  